version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rssuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rssdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
